/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useLayoutEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
export function BloodMoonJhin(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/blood_moon_jhin.glb')
    const { actions } = useAnimations(animations, group)
    console.log(actions);
    console.log(materials);
    useEffect(() => {
        for (const key in actions) {
            actions[key].stop();
            materials["Jhin_BloodMoon_MAT"].wireframe = false
        }
        if (props.actionType === "Respawn") {
            materials["Jhin_BloodMoon_MAT"].wireframe = true

        }
        actions[props.actionType].reset().play();


    }, [props.actionType])
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="AuxScene">
                <group position={props.position}>
                    <group name="Meshes" scale={[-0.009, 0.009, 0.009]}>
                        <group position={[-49.604, -21.544, -40.752]} scale={0.014}>
                            <skinnedMesh
                                name="mesh_0"
                                geometry={nodes.mesh_0.geometry}
                                material={materials.Jhin_BloodMoon_MAT}
                                skeleton={nodes.mesh_0.skeleton}
                            />
                        </group>
                    </group>
                    <group name="Skeleton" scale={[-0.009, 0.009, 0.009]}>
                        <primitive object={nodes.Root} />
                        <primitive object={nodes.Snap_Hat2World_Skin01} />
                        <primitive object={nodes.Buffbone_Glb_Channel_Loc} />
                        <primitive object={nodes.Buffbone_Glb_Ground_Loc} />
                        <primitive object={nodes.C_Buffbone_Glb_Center_Loc} />
                        <primitive object={nodes.C_Buffbone_Glb_Layout_Loc} />
                        <primitive object={nodes.C_Buffbone_Glb_Overhead_Loc} />
                        <primitive object={nodes.Snap_Weapon2World} />
                        <primitive object={nodes.Snap_Sword2World} />
                        <primitive object={nodes.Skin2_Brush_Root} />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/blood_moon_jhin.glb')
