/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useLayoutEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three';
import { useFrame } from '@react-three/fiber';

export function HighNoonJhin(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF(`${props.model}`)
    const { actions } = useAnimations(animations, group)
    useEffect(() => {
        for (const key in actions) {
            actions[key].stop();
            materials["Jihn_Skin01_MAT"].wireframe = false
            materials["Jihn_Mesh_Only_Jihn_Skin01_MAT"].wireframe = false
        }
        if (props.actionType === "Respawn") {
            materials["Jihn_Skin01_MAT"].wireframe = true
            materials["Jihn_Mesh_Only_Jihn_Skin01_MAT"].wireframe = true
        }
        actions[props.actionType].reset().play();


    }, [props.actionType])


    return (
        <group ref={group} {...props} dispose={null}>
            <group name="AuxScene">
                <group position={props.position}>
                    <group name="Meshes" scale={[-0.009, 0.009, 0.009]}>
                        <group position={[-64.585, -3.708, -28.334]} scale={0.012}>
                            <skinnedMesh
                                name="mesh_0"
                                geometry={nodes.mesh_0.geometry}
                                material={materials.Jihn_Mesh_Only_Jihn_Skin01_MAT}
                                skeleton={nodes.mesh_0.skeleton}

                            />
                            <skinnedMesh
                                name="mesh_0_1"
                                geometry={nodes.mesh_0_1.geometry}
                                material={materials.Jihn_Skin01_MAT}
                                skeleton={nodes.mesh_0_1.skeleton}

                            />
                            <skinnedMesh
                                name="mesh_0_3"
                                geometry={nodes.mesh_0_3.geometry}
                                material={materials.Deadeye_Skin01_Shoulders_LOW_initialShadingGroup1}
                                skeleton={nodes.mesh_0_3.skeleton}

                            />
                        </group>
                    </group>
                    <group name="Skeleton" scale={[-0.009, 0.009, 0.009]}>
                        <primitive object={nodes.Root} />
                        <primitive object={nodes.Buffbone_Glb_Channel_Loc} />
                        <primitive object={nodes.C_Buffbone_Glb_Layout_Loc} />
                        <primitive object={nodes.Buffbone_Glb_Ground_Loc} />
                        <primitive object={nodes.Snap_Sword2World} />
                        <primitive object={nodes.Snap_Weapon2World} />
                        <primitive object={nodes.C_Buffbone_Glb_Center_Loc} />
                        <primitive object={nodes.C_Buffbone_Glb_Overhead_Loc} />
                        <primitive object={nodes.Snap_Hat2World_Skin01} />
                        <primitive object={nodes.Bar_Skin01} />
                        <primitive object={nodes.Bottle2_Skin01} />
                        <primitive object={nodes.Bottle3_Skin01} />
                        <primitive object={nodes.Bottle4_Skin01} />
                        <primitive object={nodes.Bottle5_Skin01} />
                        <primitive object={nodes.Bottle1_Skin01} />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/high_noon_jhin.glb')
