/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useLayoutEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
export function OgJhin(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/jhin.glb')
    const { actions } = useAnimations(animations, group)
    useEffect(() => {
        for (const key in actions) {
            actions[key].stop();
            materials["base_mat"].wireframe = false
        }
        if (props.actionType === "Respawn") {
            materials["base_mat"].wireframe = true
        }
        actions[props.actionType].reset().play();


    }, [props.actionType])


    return (
        <group ref={group} {...props} dispose={null}>
            <group name="AuxScene">
                <group position={props.position}>
                    <group name="Meshes" scale={[-0.009, 0.009, 0.009]}>
                        <skinnedMesh
                            name="mesh_0"
                            geometry={nodes.mesh_0.geometry}
                            material={materials.base_mat}
                            skeleton={nodes.mesh_0.skeleton}
                            position={[-47.093, -20.249, -30.155]}
                            scale={0.012}
                        />
                    </group>
                    <group name="Skeleton" scale={[-0.009, 0.009, 0.009]}>
                        <primitive object={nodes.Root} />
                        <primitive object={nodes.Snap_Hat2World_Skin01} />
                        <primitive object={nodes.Buffbone_Glb_Channel_Loc} />
                        <primitive object={nodes.Buffbone_Glb_Ground_Loc} />
                        <primitive object={nodes.C_Buffbone_Glb_Center_Loc} />
                        <primitive object={nodes.C_Buffbone_Glb_Layout_Loc} />
                        <primitive object={nodes.C_Buffbone_Glb_Overhead_Loc} />
                        <primitive object={nodes.Snap_Weapon2World} />
                        <primitive object={nodes.Snap_Sword2World} />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/jhin.glb')